services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: docdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    networks:
      - app-network
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

  app:
    build: .
    container_name: document-qa-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: docdb
      DB_USER: postgres
      DB_PASSWORD: 1234
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data: